### ISSUE TITLE
[BUG]the windows build version can not be downloaded ,Please check.

### ISSUE THREAD

**Issue by Fwar** [Pamenarti/lotus-blockchain#3]
the download url from readme.md is https://elasticbeanstalk-us-west-2-793349189011.s3.us-west-2.amazonaws.com/Lotus-win32-x64.zip
but it's not downloadable.

**Comment by edwanh** [comment]
same issue

**Comment by volklala** [comment]
same

**Comment by 1617176084** [comment]
same issue

**Comment by Pamenarti** [comment]
fixed

**Comment by edwanh** [comment]
![E9802F9E-A2C1-44F1-87E7-91BA39272D65](https://user-images.githubusercontent.com/86573426/124392545-88caf500-dcf6-11eb-81f4-d85cd526f689.png)
It is still not there please check

**Comment by Fwar** [comment]
> fixed

nop,it is still not working

**Comment by Pamenarti** [comment]
will be up and running soon.

**Comment by cantu12** [comment]
another shit launch with no client for windows, only for linux "experts", not fair at all, go to hell... hehehe

**Comment by Pamenarti** [comment]
> another shit launch with no client for windows, only for linux "experts", not fair at all, go to hell... hehehe

çalışmalar devam ediyor. biz açacağız demedik açmaya çalışıyoruz. yakında çalıştığında tekrar gelir kontrol edersin.
